version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
